apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: shareprocessns
  name: shareprocessns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shareprocessns
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shareprocessns
    spec:
      serviceAccountName: shareps
      containers:
        - image: ylinyang/shareprocessns
          name: shareprocessns
          resources: {}
status: {}