# permissions for end users to view dogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dog-viewer-role
rules:
- apiGroups:
  - d.y.demo.io
  resources:
  - dogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - d.y.demo.io
  resources:
  - dogs/status
  verbs:
  - get
