# permissions for end users to edit dogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dog-editor-role
rules:
- apiGroups:
  - d.y.demo.io
  resources:
  - dogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - d.y.demo.io
  resources:
  - dogs/status
  verbs:
  - get
