apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: shareps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shareps
subjects:
- kind: ServiceAccount
  name: shareps
  namespace: kube-system